// Generated by gencpp from file robot1_remote/Robot1TaskActionGoal.msg
// DO NOT EDIT!


#ifndef ROBOT1_REMOTE_MESSAGE_ROBOT1TASKACTIONGOAL_H
#define ROBOT1_REMOTE_MESSAGE_ROBOT1TASKACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <robot1_remote/Robot1TaskGoal.h>

namespace robot1_remote
{
template <class ContainerAllocator>
struct Robot1TaskActionGoal_
{
  typedef Robot1TaskActionGoal_<ContainerAllocator> Type;

  Robot1TaskActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  Robot1TaskActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::robot1_remote::Robot1TaskGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct Robot1TaskActionGoal_

typedef ::robot1_remote::Robot1TaskActionGoal_<std::allocator<void> > Robot1TaskActionGoal;

typedef boost::shared_ptr< ::robot1_remote::Robot1TaskActionGoal > Robot1TaskActionGoalPtr;
typedef boost::shared_ptr< ::robot1_remote::Robot1TaskActionGoal const> Robot1TaskActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator1> & lhs, const ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator1> & lhs, const ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot1_remote

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25dbc7123bf39d0ae8bdb43ed5637e31";
  }

  static const char* value(const ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25dbc7123bf39d0aULL;
  static const uint64_t static_value2 = 0xe8bdb43ed5637e31ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot1_remote/Robot1TaskActionGoal";
  }

  static const char* value(const ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"Robot1TaskGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: robot1_remote/Robot1TaskGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int64 task_number\n"
;
  }

  static const char* value(const ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Robot1TaskActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot1_remote::Robot1TaskActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::robot1_remote::Robot1TaskGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT1_REMOTE_MESSAGE_ROBOT1TASKACTIONGOAL_H
