robot1:

  # Arm Trajectory Controllers 
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5


  # Gripper Trajectory Controllers 
  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint6
