(cl:defpackage robot1_remote-msg
  (:use )
  (:export
   "<ROBOT1TASKACTION>"
   "ROBOT1TASKACTION"
   "<ROBOT1TASKACTIONFEEDBACK>"
   "ROBOT1TASKACTIONFEEDBACK"
   "<ROBOT1TASKACTIONGOAL>"
   "ROBOT1TASKACTIONGOAL"
   "<ROBOT1TASKACTIONRESULT>"
   "ROBOT1TASKACTIONRESULT"
   "<ROBOT1TASKFEEDBACK>"
   "ROBOT1TASKFEEDBACK"
   "<ROBOT1TASKGOAL>"
   "ROBOT1TASKGOAL"
   "<ROBOT1TASKRESULT>"
   "ROBOT1TASKRESULT"
  ))

