; Auto-generated. Do not edit!


(cl:in-package robot1_remote-msg)


;//! \htmlinclude Robot1TaskGoal.msg.html

(cl:defclass <Robot1TaskGoal> (roslisp-msg-protocol:ros-message)
  ((task_number
    :reader task_number
    :initarg :task_number
    :type cl:integer
    :initform 0))
)

(cl:defclass Robot1TaskGoal (<Robot1TaskGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Robot1TaskGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Robot1TaskGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot1_remote-msg:<Robot1TaskGoal> is deprecated: use robot1_remote-msg:Robot1TaskGoal instead.")))

(cl:ensure-generic-function 'task_number-val :lambda-list '(m))
(cl:defmethod task_number-val ((m <Robot1TaskGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot1_remote-msg:task_number-val is deprecated.  Use robot1_remote-msg:task_number instead.")
  (task_number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Robot1TaskGoal>) ostream)
  "Serializes a message object of type '<Robot1TaskGoal>"
  (cl:let* ((signed (cl:slot-value msg 'task_number)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Robot1TaskGoal>) istream)
  "Deserializes a message object of type '<Robot1TaskGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'task_number) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Robot1TaskGoal>)))
  "Returns string type for a message object of type '<Robot1TaskGoal>"
  "robot1_remote/Robot1TaskGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Robot1TaskGoal)))
  "Returns string type for a message object of type 'Robot1TaskGoal"
  "robot1_remote/Robot1TaskGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Robot1TaskGoal>)))
  "Returns md5sum for a message object of type '<Robot1TaskGoal>"
  "a44f0e3523e87134465bfb1a1ffe53cc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Robot1TaskGoal)))
  "Returns md5sum for a message object of type 'Robot1TaskGoal"
  "a44f0e3523e87134465bfb1a1ffe53cc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Robot1TaskGoal>)))
  "Returns full string definition for message of type '<Robot1TaskGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int64 task_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Robot1TaskGoal)))
  "Returns full string definition for message of type 'Robot1TaskGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%int64 task_number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Robot1TaskGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Robot1TaskGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'Robot1TaskGoal
    (cl:cons ':task_number (task_number msg))
))
