; Auto-generated. Do not edit!


(cl:in-package robot1_remote-msg)


;//! \htmlinclude Robot1TaskResult.msg.html

(cl:defclass <Robot1TaskResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass Robot1TaskResult (<Robot1TaskResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Robot1TaskResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Robot1TaskResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot1_remote-msg:<Robot1TaskResult> is deprecated: use robot1_remote-msg:Robot1TaskResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <Robot1TaskResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot1_remote-msg:success-val is deprecated.  Use robot1_remote-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Robot1TaskResult>) ostream)
  "Serializes a message object of type '<Robot1TaskResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Robot1TaskResult>) istream)
  "Deserializes a message object of type '<Robot1TaskResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Robot1TaskResult>)))
  "Returns string type for a message object of type '<Robot1TaskResult>"
  "robot1_remote/Robot1TaskResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Robot1TaskResult)))
  "Returns string type for a message object of type 'Robot1TaskResult"
  "robot1_remote/Robot1TaskResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Robot1TaskResult>)))
  "Returns md5sum for a message object of type '<Robot1TaskResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Robot1TaskResult)))
  "Returns md5sum for a message object of type 'Robot1TaskResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Robot1TaskResult>)))
  "Returns full string definition for message of type '<Robot1TaskResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Robot1TaskResult)))
  "Returns full string definition for message of type 'Robot1TaskResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Robot1TaskResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Robot1TaskResult>))
  "Converts a ROS message object to a list"
  (cl:list 'Robot1TaskResult
    (cl:cons ':success (success msg))
))
