; Auto-generated. Do not edit!


(cl:in-package robot1_remote-msg)


;//! \htmlinclude Robot1TaskFeedback.msg.html

(cl:defclass <Robot1TaskFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage
    :reader percentage
    :initarg :percentage
    :type cl:integer
    :initform 0))
)

(cl:defclass Robot1TaskFeedback (<Robot1TaskFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Robot1TaskFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Robot1TaskFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot1_remote-msg:<Robot1TaskFeedback> is deprecated: use robot1_remote-msg:Robot1TaskFeedback instead.")))

(cl:ensure-generic-function 'percentage-val :lambda-list '(m))
(cl:defmethod percentage-val ((m <Robot1TaskFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot1_remote-msg:percentage-val is deprecated.  Use robot1_remote-msg:percentage instead.")
  (percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Robot1TaskFeedback>) ostream)
  "Serializes a message object of type '<Robot1TaskFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'percentage)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Robot1TaskFeedback>) istream)
  "Deserializes a message object of type '<Robot1TaskFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'percentage) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Robot1TaskFeedback>)))
  "Returns string type for a message object of type '<Robot1TaskFeedback>"
  "robot1_remote/Robot1TaskFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Robot1TaskFeedback)))
  "Returns string type for a message object of type 'Robot1TaskFeedback"
  "robot1_remote/Robot1TaskFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Robot1TaskFeedback>)))
  "Returns md5sum for a message object of type '<Robot1TaskFeedback>"
  "face31f38d20abbde445df7aa912bb07")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Robot1TaskFeedback)))
  "Returns md5sum for a message object of type 'Robot1TaskFeedback"
  "face31f38d20abbde445df7aa912bb07")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Robot1TaskFeedback>)))
  "Returns full string definition for message of type '<Robot1TaskFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int64 percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Robot1TaskFeedback)))
  "Returns full string definition for message of type 'Robot1TaskFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int64 percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Robot1TaskFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Robot1TaskFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'Robot1TaskFeedback
    (cl:cons ':percentage (percentage msg))
))
