controller_list:
  - name: fake_robot1_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_robot1_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint6
initial:  # Define initial robot poses per group
  - group: robot1_arm
    pose: home