// Generated by gencpp from file robot1_chat/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROBOT1_CHAT_MESSAGE_ADDTWOINTS_H
#define ROBOT1_CHAT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <robot1_chat/AddTwoIntsRequest.h>
#include <robot1_chat/AddTwoIntsResponse.h>


namespace robot1_chat
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace robot1_chat


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot1_chat::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::robot1_chat::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::robot1_chat::AddTwoInts > {
  static const char* value()
  {
    return "robot1_chat/AddTwoInts";
  }

  static const char* value(const ::robot1_chat::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::robot1_chat::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::robot1_chat::AddTwoInts >
template<>
struct MD5Sum< ::robot1_chat::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot1_chat::AddTwoInts >::value();
  }
  static const char* value(const ::robot1_chat::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot1_chat::AddTwoIntsRequest> should match
// service_traits::DataType< ::robot1_chat::AddTwoInts >
template<>
struct DataType< ::robot1_chat::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::robot1_chat::AddTwoInts >::value();
  }
  static const char* value(const ::robot1_chat::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot1_chat::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::robot1_chat::AddTwoInts >
template<>
struct MD5Sum< ::robot1_chat::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot1_chat::AddTwoInts >::value();
  }
  static const char* value(const ::robot1_chat::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot1_chat::AddTwoIntsResponse> should match
// service_traits::DataType< ::robot1_chat::AddTwoInts >
template<>
struct DataType< ::robot1_chat::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::robot1_chat::AddTwoInts >::value();
  }
  static const char* value(const ::robot1_chat::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT1_CHAT_MESSAGE_ADDTWOINTS_H
