// Generated by gencpp from file robot1_controller/AnglesConverter.msg
// DO NOT EDIT!


#ifndef ROBOT1_CONTROLLER_MESSAGE_ANGLESCONVERTER_H
#define ROBOT1_CONTROLLER_MESSAGE_ANGLESCONVERTER_H

#include <ros/service_traits.h>


#include <robot1_controller/AnglesConverterRequest.h>
#include <robot1_controller/AnglesConverterResponse.h>


namespace robot1_controller
{

struct AnglesConverter
{

typedef AnglesConverterRequest Request;
typedef AnglesConverterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnglesConverter
} // namespace robot1_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot1_controller::AnglesConverter > {
  static const char* value()
  {
    return "520baf98315cffffbe617b7c68675a94";
  }

  static const char* value(const ::robot1_controller::AnglesConverter&) { return value(); }
};

template<>
struct DataType< ::robot1_controller::AnglesConverter > {
  static const char* value()
  {
    return "robot1_controller/AnglesConverter";
  }

  static const char* value(const ::robot1_controller::AnglesConverter&) { return value(); }
};


// service_traits::MD5Sum< ::robot1_controller::AnglesConverterRequest> should match
// service_traits::MD5Sum< ::robot1_controller::AnglesConverter >
template<>
struct MD5Sum< ::robot1_controller::AnglesConverterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot1_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robot1_controller::AnglesConverterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot1_controller::AnglesConverterRequest> should match
// service_traits::DataType< ::robot1_controller::AnglesConverter >
template<>
struct DataType< ::robot1_controller::AnglesConverterRequest>
{
  static const char* value()
  {
    return DataType< ::robot1_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robot1_controller::AnglesConverterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot1_controller::AnglesConverterResponse> should match
// service_traits::MD5Sum< ::robot1_controller::AnglesConverter >
template<>
struct MD5Sum< ::robot1_controller::AnglesConverterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot1_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robot1_controller::AnglesConverterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot1_controller::AnglesConverterResponse> should match
// service_traits::DataType< ::robot1_controller::AnglesConverter >
template<>
struct DataType< ::robot1_controller::AnglesConverterResponse>
{
  static const char* value()
  {
    return DataType< ::robot1_controller::AnglesConverter >::value();
  }
  static const char* value(const ::robot1_controller::AnglesConverterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT1_CONTROLLER_MESSAGE_ANGLESCONVERTER_H
